import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import { migrate } from "drizzle-orm/pglite/migrator";
import { withDrizzleAudit } from "../../src/index.ts";
import { drizzleTableStorage } from "../../src/storage/drizzle.ts";
import { mask } from "../../src/transforms/index.ts";
import * as schema from "./schema.ts";

const client = new PGlite();
const rawDb = drizzle(client, { schema });

// Run migrations — generated by `drizzle-kit generate` from schema.ts
const migrationsFolder = new URL("./migrations", import.meta.url).pathname;
await migrate(rawDb, { migrationsFolder });

// Seed
await rawDb.insert(schema.users).values([
  { name: "Alice Johnson", email: "alice@example.com", role: "admin" },
  { name: "Bob Smith", email: "bob@example.com", role: "user" },
  { name: "Charlie Brown", email: "charlie@example.com", role: "user" },
]);

export const db = withDrizzleAudit(rawDb, {
  storage: drizzleTableStorage(schema.auditLog, { db: rawDb }),
  auditTable: schema.auditLog,
  tables: {
    users: {
      transforms: [mask("email")],
    },
  },
});

export { rawDb };
