import { mysqlTable, bigint, varchar, text, json, timestamp, index } from "drizzle-orm/mysql-core";

/**
 * Controls the type of primary key used for a MySQL audit table.
 *
 * - `"uuid"` — A `varchar(36)` column storing a UUID generated by `crypto.randomUUID()`. Default.
 * - `"serial"` — A `bigint` auto-incrementing column (equivalent to `BIGINT UNSIGNED AUTO_INCREMENT`).
 *
 * @example
 * ```ts
 * const auditLog = mysqlAuditTable("audit_log", { idMode: "serial" });
 * ```
 */
export type AuditIdMode = "uuid" | "serial";

/**
 * Options for {@link mysqlAuditTable}.
 *
 * @example
 * ```ts
 * const auditLog = mysqlAuditTable("audit_log", {
 *   idMode: "uuid",
 *   extraColumns: () => ({
 *     tenantId: varchar("tenant_id", { length: 36 }).notNull(),
 *   }),
 * });
 * ```
 */
export interface MysqlAuditTableOptions {
  /**
   * The type of primary key to use for the audit table.
   * Defaults to `"uuid"`.
   */
  idMode?: AuditIdMode;
  /**
   * A factory function that returns additional Drizzle column definitions to
   * include in the audit table. Useful for adding tenant IDs, environment
   * tags, or any other application-specific columns.
   *
   * @example
   * ```ts
   * extraColumns: () => ({
   *   tenantId: varchar("tenant_id", { length: 36 }).notNull(),
   *   env: varchar("env", { length: 20 }),
   * })
   * ```
   */
  extraColumns?: () => Record<string, any>;
}

/**
 * Creates a Drizzle ORM table definition for storing audit log entries in
 * MySQL.
 *
 * The table includes the standard audit columns (`id`, `table_name`, `action`,
 * `row_id`, `changes`, `old_data`, `new_data`, `user_id`, `metadata`,
 * `timestamp`) with appropriate indexes pre-configured. JSON columns use
 * MySQL's native `json` type. The `timestamp` column uses `TIMESTAMP DEFAULT NOW()`.
 *
 * @param name - The SQL table name. Defaults to `"audit_log"`.
 * @param options - Optional configuration for id mode and extra columns.
 * @returns A Drizzle `mysqlTable` definition ready to use with migrations and
 *   `drizzleTableStorage`.
 *
 * @example
 * ```ts
 * // schema.ts — default UUID primary key
 * import { mysqlAuditTable } from "drizzle-audit/schema/mysql";
 *
 * export const auditLog = mysqlAuditTable("audit_log");
 * ```
 *
 * @example
 * ```ts
 * // schema.ts — serial primary key with a custom tenant column
 * export const auditLog = mysqlAuditTable("audit_log", {
 *   idMode: "serial",
 *   extraColumns: () => ({
 *     tenantId: varchar("tenant_id", { length: 36 }).notNull(),
 *   }),
 * });
 * ```
 */
export function mysqlAuditTable(name = "audit_log", options?: MysqlAuditTableOptions) {
  const idMode = options?.idMode ?? "uuid";

  const idColumn =
    idMode === "serial"
      ? { id: bigint("id", { mode: "number" }).primaryKey().autoincrement() }
      : {
          id: varchar("id", { length: 36 })
            .primaryKey()
            .$defaultFn(() => crypto.randomUUID()),
        };

  return mysqlTable(
    name,
    {
      ...idColumn,
      tableName: text("table_name"),
      action: varchar("action", { length: 50 }).notNull(),
      rowId: text("row_id"),
      changes: json("changes"),
      oldData: json("old_data"),
      newData: json("new_data"),
      userId: text("user_id"),
      metadata: json("metadata"),
      timestamp: timestamp("timestamp").notNull().defaultNow(),
      ...options?.extraColumns?.(),
    },
    (table) => [
      index(`${name}_table_name_idx`).on(table.tableName),
      index(`${name}_row_id_idx`).on(table.rowId),
      index(`${name}_user_id_idx`).on(table.userId),
      index(`${name}_action_idx`).on(table.action),
      index(`${name}_timestamp_idx`).on(table.timestamp),
    ],
  );
}
