import { sqliteTable, integer, text, index } from "drizzle-orm/sqlite-core";

/**
 * Controls the type of primary key used for a SQLite audit table.
 *
 * - `"uuid"` — A `text` column storing a UUID generated by `crypto.randomUUID()`. Default.
 * - `"integer"` — An auto-incrementing `integer` primary key (rowid alias).
 *
 * @example
 * ```ts
 * const auditLog = sqliteAuditTable("audit_log", { idMode: "integer" });
 * ```
 */
export type AuditIdMode = "uuid" | "integer";

/**
 * Options for {@link sqliteAuditTable}.
 *
 * @example
 * ```ts
 * const auditLog = sqliteAuditTable("audit_log", {
 *   idMode: "uuid",
 *   extraColumns: () => ({
 *     env: text("env"),
 *   }),
 * });
 * ```
 */
export interface SqliteAuditTableOptions {
  /**
   * The type of primary key to use for the audit table.
   * Defaults to `"uuid"`.
   */
  idMode?: AuditIdMode;
  /**
   * A factory function that returns additional Drizzle column definitions to
   * include in the audit table. Useful for adding tenant IDs, environment
   * tags, or any other application-specific columns.
   *
   * @example
   * ```ts
   * extraColumns: () => ({
   *   env: text("env"),
   *   region: text("region"),
   * })
   * ```
   */
  extraColumns?: () => Record<string, any>;
}

/**
 * Creates a Drizzle ORM table definition for storing audit log entries in
 * SQLite.
 *
 * The table includes the standard audit columns (`id`, `table_name`, `action`,
 * `row_id`, `changes`, `old_data`, `new_data`, `user_id`, `metadata`,
 * `timestamp`) with appropriate indexes pre-configured. JSON columns are
 * stored as text with `mode: "json"`. The `timestamp` column is stored as an
 * ISO 8601 text string.
 *
 * @param name - The SQL table name. Defaults to `"audit_log"`.
 * @param options - Optional configuration for id mode and extra columns.
 * @returns A Drizzle `sqliteTable` definition ready to use with migrations and
 *   `drizzleTableStorage`.
 *
 * @example
 * ```ts
 * // schema.ts — default UUID primary key
 * import { sqliteAuditTable } from "drizzle-audit/schema/sqlite";
 *
 * export const auditLog = sqliteAuditTable("audit_log");
 * ```
 *
 * @example
 * ```ts
 * // schema.ts — integer primary key with an extra env column
 * export const auditLog = sqliteAuditTable("audit_log", {
 *   idMode: "integer",
 *   extraColumns: () => ({
 *     env: text("env"),
 *   }),
 * });
 * ```
 */
export function sqliteAuditTable(name = "audit_log", options?: SqliteAuditTableOptions) {
  const idMode = options?.idMode ?? "uuid";

  const idColumn =
    idMode === "integer"
      ? { id: integer("id").primaryKey({ autoIncrement: true }) }
      : {
          id: text("id")
            .primaryKey()
            .$defaultFn(() => crypto.randomUUID()),
        };

  return sqliteTable(
    name,
    {
      ...idColumn,
      tableName: text("table_name"),
      action: text("action").notNull(),
      rowId: text("row_id"),
      changes: text("changes", { mode: "json" }),
      oldData: text("old_data", { mode: "json" }),
      newData: text("new_data", { mode: "json" }),
      userId: text("user_id"),
      metadata: text("metadata", { mode: "json" }),
      timestamp: text("timestamp")
        .notNull()
        .$defaultFn(() => new Date().toISOString()),
      ...options?.extraColumns?.(),
    },
    (table) => [
      index(`${name}_table_name_idx`).on(table.tableName),
      index(`${name}_row_id_idx`).on(table.rowId),
      index(`${name}_user_id_idx`).on(table.userId),
      index(`${name}_action_idx`).on(table.action),
      index(`${name}_timestamp_idx`).on(table.timestamp),
    ],
  );
}
